### ISSUE TITLE
Cannot override systemd AmbientCapabilities

### ISSUE THREAD

**Issue by DJViking** [jenkinsci/packaging#297]
### Jenkins and plugins versions report

With #285, Jenkins got support on systemd with port numbers less than 1024.
When migrating over, I discovered setting the `AmbientCapabilities` in `override.conf` using `systemctl edit jenkins` does not work. I had to set it directly in the file `jenkins.service`, a file which should not be edited.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Run `systemctl edit jenkins`
2. Change JENKINS_HTTPS_PORT to 443 or JENKINS_PORT to 80
3. Add Environment="AmbientCapabilities=CAP_NET_BIND_SERVICE"

### Expected Results

Jenkins running on port 443/80

### Actual Results

2022-03-11 09:55:00.419+0000 [id=1]     SEVERE  winstone.Logger#logInternal: Container startup failed
java.net.SocketException: Permission denied
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
Caused: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:443

**Comment by timja** [comment]
You shouldn't set it as an Environment directive it should be on it's own line in the override file

**Comment by DJViking** [comment]
Ok.
Now I realise I was so fixed on the Environment. Looking again now in the jenkins.service I see that `AmbientCapabilities` is on its own.
