### ISSUE TITLE
jenkins.tmpfiles missing from Debian package

### ISSUE THREAD

**Issue by TobiX** [jenkinsci/packaging#455]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.440.2
OS: Linux - 6.1.0-18-amd64
Java: 17.0.10 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:4.21.0
amazon-ecr:1.114.vfd22430621f5
analysis-model-api:12.1.0
ansicolor:1.0.4
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
asm-api:9.6-3.v2e1fa_b_338cd7
authentication-tokens:1.53.v1c90fd9191a_b_
aws-credentials:218.v1b_e9466ec5da_
aws-java-sdk-ec2:1.12.671-439.veec746c91fcb_
aws-java-sdk-ecr:1.12.671-439.veec746c91fcb_
aws-java-sdk-minimal:1.12.671-439.veec746c91fcb_
azure-ad:457.vf85d61f83b_26
azure-sdk:157.v855da_0b_eb_dc2
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1152.v6f101e97dd77
build-monitor-plugin:1.14-860.vd06ef2568b_3f
build-user-vars-plugin:1.9
buildtriggerbadge:251.vdf6ef853f3f5
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-folder:6.901.vb_4c7a_da_75da_3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
compact-columns:1.185.vf3851b_4d31fe
config-file-provider:968.ve1ca_eb_913f8c
copyartifact:722.v0662a_9b_e22a_c
coverage:1.13.0
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:657.v2b_19db_7d6e6d
customizable-header:83.vf51a_828deb_b_e
dark-theme:439.vdef09f81f85e
dashboard-view:2.508.va_74654f026d1
data-tables-api:2.0.2-1
database:230.v701f20b_8b_f95
database-postgresql:100.v2418e0a_c6909
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
downstream-build-cache:1.7
durable-task:550.v0930093c4b_a_6
echarts-api:5.5.0-1
email-ext:2.105
embeddable-build-status:467.v4a_954796e45d
extra-columns:1.26
favorite:2.208.v91d65b_7792a_c
flyway-api:9.22.3-75.vfdfb_f75a_a_9b_e
font-awesome-api:6.5.1-3
forensics-api:2.4.0
git:5.2.1
git-client:4.7.0
git-forensics:2.1.0
git-parameter:0.9.19
gitlab-api:5.3.0-91.v1f9a_fda_d654f
gitlab-branch-source:703.vc5fd7effcc6b_
gitlab-scm-filter-aged-refs:39.ve2e68cc3fa_78
groovy:457.v99900cb_85593
gson-api:2.10.1-15.v0d99f670e0a_7
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.33
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jersey2-api:2.41-133.va_03323b_a_1396
jira:3.13
job-dsl:1.87
jobConfigHistory:1229.v3039470161a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery3-api:3.7.1-2
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-52.v57de85cc4722
junit:1259.v65ffcef24a_88
junit-attachments:205.vc0677977deb_0
junit-sql-storage:282.v0b_9d0f91b_cec
kubernetes:4203.v1dd44f5b_1cf9
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:0.11
lockable-resources:1246.v28b_e4cc6fa_16
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.2.2
matrix-project:822.824.v14451b_c0fd42
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
next-executions:310.v52e770651319
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
performance:957.v658a_7065b_92a_
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-graph-view:232.vc7ca_8d934725
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:491.vb_07d21da_1a_fb_
pipeline-maven:1390.v66456b_ea_3467
pipeline-maven-api:1390.v66456b_ea_3467
pipeline-maven-database:1390.v66456b_ea_3467
pipeline-model-api:2.2184.v0b_358b_953e69
pipeline-model-definition:2.2184.v0b_358b_953e69
pipeline-model-extensions:2.2184.v0b_358b_953e69
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2184.v0b_358b_953e69
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:179.vc5cb_98f6db_38
platformlabeler:2325.v8f074df8840d
plugin-util-api:4.1.0
postgresql-api:42.7.2-40.v76d376d65c77
prism-api:1.29.0-13
role-strategy:713.vb_3837801b_8cc
s3:466.vf5b_3db_8e3eb_2
scm-api:689.v237b_6d3a_ef7f
script-security:1326.vdb_c154de8669
simple-theme-plugin:176.v39740c03a_a_f5
snakeyaml-api:2.2-111.vc6598e30cc65
sonar:2.17.2
ssh-agent:346.vda_a_c4f2c8e50
ssh-credentials:326.v7fcb_a_ef6194b_
ssh-slaves:2.948.vb_8050d697fec
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
subversion:2.17.3
test-results-analyzer:0.4.1
text-finder:1.26
theme-manager:215.vc1ff18d67920
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
variant:60.v7290fc0eb_b_cd
versioncolumn:243.vda_c20eea_a_8a_f
view-job-filters:369.ve0513a_a_f5524
warnings-ng:11.2.2
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1049.v257a_e6b_30fb_d
workflow-cps:3883.vb_3ff2a_e3eea_f
workflow-durable-task-step:1331.vc8c2fed35334
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:881.v7663695646cf
yet-another-build-visualizer:1.16
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Debian 12

### Reproduction steps

1. Add `Environment="JENKINS_UNIX_DOMAIN_PATH=/run/jenkins/jenkins.socket"` to /etc/systemd/system/jenkins.service.d/override.conf
2. Restart Jenkins

### Expected Results

Clean restart, with a new socket in /run/jenkins/jenkins.socket

### Actual Results

Fails, because `/run/jenkins` does not exist:
```
jenkins[351226]: java.io.IOException: Failed to start Jetty
jenkins[351226]:         at winstone.Launcher.<init>(Launcher.java:209)
jenkins[351226]:         at winstone.Launcher.main(Launcher.java:496)
jenkins[351226]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins[351226]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jenkins[351226]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jenkins[351226]:         at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jenkins[351226]:         at executable.Main.main(Main.java:351)
jenkins[351226]: Caused by: java.io.IOException: Could not bind UnixDomainServerConnector to /run/jenkins/jenkins.socket
jenkins[351226]:         at org.eclipse.jetty.unixdomain.server.UnixDomainServerConnector.bindServerSocketChannel(UnixDomainServerConnector.java:267)
jenkins[351226]:         at org.eclipse.jetty.unixdomain.server.UnixDomainServerConnector.openServerSocketChannel(UnixDomainServerConnector.java:234)
jenkins[351226]:         at org.eclipse.jetty.unixdomain.server.UnixDomainServerConnector.open(UnixDomainServerConnector.java:205)
jenkins[351226]:         at org.eclipse.jetty.unixdomain.server.UnixDomainServerConnector.doStart(UnixDomainServerConnector.java:153)
jenkins[351226]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
jenkins[351226]:         at org.eclipse.jetty.server.Server.doStart(Server.java:428)
jenkins[351226]:         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
jenkins[351226]:         at winstone.Launcher.<init>(Launcher.java:205)
jenkins[351226]:         ... 6 more
jenkins[351226]: Caused by: java.net.BindException: Permission denied
jenkins[351226]:         at java.base/sun.nio.ch.UnixDomainSockets.bind0(Native Method)
jenkins[351226]:         at java.base/sun.nio.ch.UnixDomainSockets.bind(Unknown Source)
jenkins[351226]:         at java.base/sun.nio.ch.ServerSocketChannelImpl.unixBind(Unknown Source)
jenkins[351226]:         at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
jenkins[351226]:         at org.eclipse.jetty.unixdomain.server.UnixDomainServerConnector.bindServerSocketChannel(UnixDomainServerConnector.java:261)
jenkins[351226]:         ... 13 more
```

### Anything else?

AFAICS, #442 should have added a tmpfiles file to the Debian package, but it didn't?!?

### Are you interested in contributing a fix?

Yes

**Comment by MarkEWaite** [comment]
Thanks for being willing to contribute the fix @TobiX .

@darinpope has more experience with Unix domain socket configurations for Jenkins than I do.  I'd love to have him be a reviewer of the pull request that you submit @TobiX.

**Comment by TobiX** [comment]
The issue is this: `debian/jenkins.tmpfiles` is the wrong name for dh compat level 10. The `s` was added in compat level 13 (see https://manpages.debian.org/bullseye/debhelper/debhelper.7.en.html#v13). I propose updating the compat level. PR incoming.
